# Generated by Django 6.0.5 on 2026-08-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=1)),
                ('price_range', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='designers/')),
            ],
        ),
    ]
